//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrosBrasInc.Ressource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ressource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ressource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrosBrasInc.Ressource.Ressource", typeof(Ressource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Article_Categorie {
            get {
                return ResourceManager.GetString("Article_Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article name.
        /// </summary>
        public static string Article_NomArticle {
            get {
                return ResourceManager.GetString("Article_NomArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Article_Prix {
            get {
                return ResourceManager.GetString("Article_Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category name.
        /// </summary>
        public static string Categorie_NomCategorie {
            get {
                return ResourceManager.GetString("Categorie_NomCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string Client_CardNumber {
            get {
                return ResourceManager.GetString("Client_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paypal Url.
        /// </summary>
        public static string Client_PaypalUrl {
            get {
                return ResourceManager.GetString("Client_PaypalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clients.
        /// </summary>
        public static string Commande_Client {
            get {
                return ResourceManager.GetString("Commande_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtotal.
        /// </summary>
        public static string Commande_SousTotal {
            get {
                return ResourceManager.GetString("Commande_SousTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxes.
        /// </summary>
        public static string Commande_Taxes {
            get {
                return ResourceManager.GetString("Commande_Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Commande_Total {
            get {
                return ResourceManager.GetString("Commande_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Author.
        /// </summary>
        public static string Forum_Message_Author {
            get {
                return ResourceManager.GetString("Forum_Message_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Body.
        /// </summary>
        public static string Forum_Message_MessageBody {
            get {
                return ResourceManager.GetString("Forum_Message_MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parent subject.
        /// </summary>
        public static string Forum_Message_ParentSujet {
            get {
                return ResourceManager.GetString("Forum_Message_ParentSujet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject body.
        /// </summary>
        public static string Forum_Subject_SubjectBody {
            get {
                return ResourceManager.GetString("Forum_Subject_SubjectBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject title.
        /// </summary>
        public static string Forum_Subject_SubjectTitle {
            get {
                return ResourceManager.GetString("Forum_Subject_SubjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Global_Add {
            get {
                return ResourceManager.GetString("Global_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Global_CreateNew {
            get {
                return ResourceManager.GetString("Global_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Global_Delete {
            get {
                return ResourceManager.GetString("Global_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Global_Details {
            get {
                return ResourceManager.GetString("Global_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Global_Edit {
            get {
                return ResourceManager.GetString("Global_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support us.
        /// </summary>
        public static string Home_Index_Support {
            get {
                return ResourceManager.GetString("Home_Index_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to GrosBrasInc.
        /// </summary>
        public static string Home_Index_Welcome {
            get {
                return ResourceManager.GetString("Home_Index_Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Order_Address {
            get {
                return ResourceManager.GetString("Order_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string Order_City {
            get {
                return ResourceManager.GetString("Order_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Order_Country {
            get {
                return ResourceManager.GetString("Order_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Order_Email {
            get {
                return ResourceManager.GetString("Order_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string Order_FirstName {
            get {
                return ResourceManager.GetString("Order_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string Order_LastName {
            get {
                return ResourceManager.GetString("Order_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order date.
        /// </summary>
        public static string Order_OrderDate {
            get {
                return ResourceManager.GetString("Order_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Order_Phone {
            get {
                return ResourceManager.GetString("Order_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postal Code.
        /// </summary>
        public static string Order_PostalCode {
            get {
                return ResourceManager.GetString("Order_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State.
        /// </summary>
        public static string Order_State {
            get {
                return ResourceManager.GetString("Order_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        public static string Order_Total {
            get {
                return ResourceManager.GetString("Order_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Order_Username {
            get {
                return ResourceManager.GetString("Order_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string OrderDetails_Article {
            get {
                return ResourceManager.GetString("OrderDetails_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string OrderDetails_Quantity {
            get {
                return ResourceManager.GetString("OrderDetails_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price.
        /// </summary>
        public static string OrderDetails_UnitPrice {
            get {
                return ResourceManager.GetString("OrderDetails_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article.
        /// </summary>
        public static string Panier_Article {
            get {
                return ResourceManager.GetString("Panier_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count.
        /// </summary>
        public static string Panier_Count {
            get {
                return ResourceManager.GetString("Panier_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date created.
        /// </summary>
        public static string Panier_DateCreated {
            get {
                return ResourceManager.GetString("Panier_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to about.
        /// </summary>
        public static string View_about_title {
            get {
                return ResourceManager.GetString("View_about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string View_Contact_title {
            get {
                return ResourceManager.GetString("View_Contact_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounts.
        /// </summary>
        public static string View_terms_Accounts_title {
            get {
                return ResourceManager.GetString("View_terms_Accounts_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of use.
        /// </summary>
        public static string View_Terms_page {
            get {
                return ResourceManager.GetString("View_Terms_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See posts.
        /// </summary>
        public static string View_Voir_Posts {
            get {
                return ResourceManager.GetString("View_Voir_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At Gros Bras Inc, we strive to offer the very best in bodybuilding supplements.  With our secure website, and our premium products, Gros Bras Inc is the best solution to all your muscle needs.
        /// </summary>
        public static string Views_About_body {
            get {
                return ResourceManager.GetString("Views_About_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        public static string Views_Layout_About {
            get {
                return ResourceManager.GetString("Views_Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Articles.
        /// </summary>
        public static string Views_Layout_Articles {
            get {
                return ResourceManager.GetString("Views_Layout_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cart.
        /// </summary>
        public static string Views_Layout_Cart {
            get {
                return ResourceManager.GetString("Views_Layout_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        public static string Views_Layout_Contact {
            get {
                return ResourceManager.GetString("Views_Layout_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string Views_Layout_Forum {
            get {
                return ResourceManager.GetString("Views_Layout_Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Views_Layout_Home {
            get {
                return ResourceManager.GetString("Views_Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Views_LoginPartial_Hello {
            get {
                return ResourceManager.GetString("Views_LoginPartial_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string Views_LoginPartial_LogIn {
            get {
                return ResourceManager.GetString("Views_LoginPartial_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string Views_LoginPartial_LogOff {
            get {
                return ResourceManager.GetString("Views_LoginPartial_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Views_LoginPartial_Register {
            get {
                return ResourceManager.GetString("Views_LoginPartial_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some services on the Sites permit or require you to create an account to participate or to secure additional benefits. You agree to provide, maintain and update true, accurate, current and complete information about yourself as prompted by our registration processes (the &quot;Registration Data&quot;). You shall not impersonate any person or entity or misrepresent your identity or affiliation with any person or entity, including using another person&apos;s username, password or other account information, or another person [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Views_terms_accounts_body {
            get {
                return ResourceManager.GetString("Views_terms_accounts_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have adopted and implemented a policy that provides for the termination, in appropriate circumstances as determined by us in our sole discretion, of users who are infringers of copyright.
        ///
        ///Pursuant to Title 17, United States Code, Section 512(c)(2), notifications of claimed copyright infringement must be sent to our Designated Agent.
        ///
        ///Notification must be submitted to the following Designated Agent: Sarah Smith.
        ///
        ///Full Address of Designated Agent to Which Notification Should be Sent: 5777 N. Meeker  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Views_terms_Copy_body {
            get {
                return ResourceManager.GetString("Views_terms_Copy_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to claims of copyright infringement.
        /// </summary>
        public static string Views_terms_Copy_title {
            get {
                return ResourceManager.GetString("Views_terms_Copy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to THE CONTENT ON OR OTHERWISE RELATED IN ANY WAY TO OUR SITES OR ANY THIRD PARTY SITES OR SERVICES LINKED TO FROM ANY SITE IS PROVIDED &quot;AS IS&quot; AND WITHOUT WARRANTIES OF ANY KIND. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, AVAILABILITY, SECURITY, COMPATABILITY AND NONINFRINGEMENT. WE DO NOT WARRANT THAT ANY CONTENT WILL BE ERROR-FREE, THAT ACCESS  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Views_terms_dis_Body {
            get {
                return ResourceManager.GetString("Views_terms_dis_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disclaimer.
        /// </summary>
        public static string Views_terms_Dis_title {
            get {
                return ResourceManager.GetString("Views_terms_Dis_title", resourceCulture);
            }
        }
    }
}
