//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GrosBrasInc.Ressource {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Ressource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Ressource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GrosBrasInc.Ressource.Ressource", typeof(Ressource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à  , or simply to meet other bodybuilders!.
        /// </summary>
        public static string About_us__gym_text_2 {
            get {
                return ResourceManager.GetString("About_us__gym_text_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à In addition to selling training goodies online, we have a very complete training center, where you can come train with partners you meet on our .
        /// </summary>
        public static string About_us_gym_text_1 {
            get {
                return ResourceManager.GetString("About_us_gym_text_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Our training center.
        /// </summary>
        public static string About_us_gym_title {
            get {
                return ResourceManager.GetString("About_us_gym_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category.
        /// </summary>
        public static string Article_Categorie {
            get {
                return ResourceManager.GetString("Article_Categorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Article name.
        /// </summary>
        public static string Article_NomArticle {
            get {
                return ResourceManager.GetString("Article_NomArticle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Price.
        /// </summary>
        public static string Article_Prix {
            get {
                return ResourceManager.GetString("Article_Prix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Research.
        /// </summary>
        public static string Articles_btn_research {
            get {
                return ResourceManager.GetString("Articles_btn_research", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Category name.
        /// </summary>
        public static string Categorie_NomCategorie {
            get {
                return ResourceManager.GetString("Categorie_NomCategorie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Card Number.
        /// </summary>
        public static string Client_CardNumber {
            get {
                return ResourceManager.GetString("Client_CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Paypal Url.
        /// </summary>
        public static string Client_PaypalUrl {
            get {
                return ResourceManager.GetString("Client_PaypalUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Clients.
        /// </summary>
        public static string Commande_Client {
            get {
                return ResourceManager.GetString("Commande_Client", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subtotal.
        /// </summary>
        public static string Commande_SousTotal {
            get {
                return ResourceManager.GetString("Commande_SousTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Taxes.
        /// </summary>
        public static string Commande_Taxes {
            get {
                return ResourceManager.GetString("Commande_Taxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        public static string Commande_Total {
            get {
                return ResourceManager.GetString("Commande_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Author.
        /// </summary>
        public static string Forum_Message_Author {
            get {
                return ResourceManager.GetString("Forum_Message_Author", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Message Body.
        /// </summary>
        public static string Forum_Message_MessageBody {
            get {
                return ResourceManager.GetString("Forum_Message_MessageBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Parent subject.
        /// </summary>
        public static string Forum_Message_ParentSujet {
            get {
                return ResourceManager.GetString("Forum_Message_ParentSujet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject body.
        /// </summary>
        public static string Forum_Subject_SubjectBody {
            get {
                return ResourceManager.GetString("Forum_Subject_SubjectBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Subject title.
        /// </summary>
        public static string Forum_Subject_SubjectTitle {
            get {
                return ResourceManager.GetString("Forum_Subject_SubjectTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Add.
        /// </summary>
        public static string Global_Add {
            get {
                return ResourceManager.GetString("Global_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create New.
        /// </summary>
        public static string Global_CreateNew {
            get {
                return ResourceManager.GetString("Global_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Delete.
        /// </summary>
        public static string Global_Delete {
            get {
                return ResourceManager.GetString("Global_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Details.
        /// </summary>
        public static string Global_Details {
            get {
                return ResourceManager.GetString("Global_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Edit.
        /// </summary>
        public static string Global_Edit {
            get {
                return ResourceManager.GetString("Global_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Check our inventory of supplements and training tools.
        /// </summary>
        public static string Home_check_articles {
            get {
                return ResourceManager.GetString("Home_check_articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Discuss on our forum and get to know other bodubuilders.
        /// </summary>
        public static string Home_check_forum {
            get {
                return ResourceManager.GetString("Home_check_forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à GrosBrasInc.
        /// </summary>
        public static string Home_Index_GrosBrasInc {
            get {
                return ResourceManager.GetString("Home_Index_GrosBrasInc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Support us.
        /// </summary>
        public static string Home_Index_Support {
            get {
                return ResourceManager.GetString("Home_Index_Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Favorite products.
        /// </summary>
        public static string Home_Recommandations {
            get {
                return ResourceManager.GetString("Home_Recommandations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Visit us at our training center at Montreal.
        /// </summary>
        public static string Home_visit_us {
            get {
                return ResourceManager.GetString("Home_visit_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LogIn.
        /// </summary>
        public static string Login_button {
            get {
                return ResourceManager.GetString("Login_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Remember me?.
        /// </summary>
        public static string Login_remember_user {
            get {
                return ResourceManager.GetString("Login_remember_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Address.
        /// </summary>
        public static string Order_Address {
            get {
                return ResourceManager.GetString("Order_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à City.
        /// </summary>
        public static string Order_City {
            get {
                return ResourceManager.GetString("Order_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Country.
        /// </summary>
        public static string Order_Country {
            get {
                return ResourceManager.GetString("Order_Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Order_Email {
            get {
                return ResourceManager.GetString("Order_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à First name.
        /// </summary>
        public static string Order_FirstName {
            get {
                return ResourceManager.GetString("Order_FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Last name.
        /// </summary>
        public static string Order_LastName {
            get {
                return ResourceManager.GetString("Order_LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Order date.
        /// </summary>
        public static string Order_OrderDate {
            get {
                return ResourceManager.GetString("Order_OrderDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Phone.
        /// </summary>
        public static string Order_Phone {
            get {
                return ResourceManager.GetString("Order_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Postal Code.
        /// </summary>
        public static string Order_PostalCode {
            get {
                return ResourceManager.GetString("Order_PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à State.
        /// </summary>
        public static string Order_State {
            get {
                return ResourceManager.GetString("Order_State", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Total.
        /// </summary>
        public static string Order_Total {
            get {
                return ResourceManager.GetString("Order_Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Username.
        /// </summary>
        public static string Order_Username {
            get {
                return ResourceManager.GetString("Order_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Article.
        /// </summary>
        public static string OrderDetails_Article {
            get {
                return ResourceManager.GetString("OrderDetails_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quantity.
        /// </summary>
        public static string OrderDetails_Quantity {
            get {
                return ResourceManager.GetString("OrderDetails_Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unit price.
        /// </summary>
        public static string OrderDetails_UnitPrice {
            get {
                return ResourceManager.GetString("OrderDetails_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Article.
        /// </summary>
        public static string Panier_Article {
            get {
                return ResourceManager.GetString("Panier_Article", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Count.
        /// </summary>
        public static string Panier_Count {
            get {
                return ResourceManager.GetString("Panier_Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Date created.
        /// </summary>
        public static string Panier_DateCreated {
            get {
                return ResourceManager.GetString("Panier_DateCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register.
        /// </summary>
        public static string Register_button {
            get {
                return ResourceManager.GetString("Register_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Confirm password.
        /// </summary>
        public static string Register_confirm_password {
            get {
                return ResourceManager.GetString("Register_confirm_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Create a new account.
        /// </summary>
        public static string Register_createnew {
            get {
                return ResourceManager.GetString("Register_createnew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Email.
        /// </summary>
        public static string Register_email {
            get {
                return ResourceManager.GetString("Register_email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Password.
        /// </summary>
        public static string Register_password {
            get {
                return ResourceManager.GetString("Register_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The password and confirmation password do not match..
        /// </summary>
        public static string Register_password_compare {
            get {
                return ResourceManager.GetString("Register_password_compare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About.
        /// </summary>
        public static string View_about_title {
            get {
                return ResourceManager.GetString("View_about_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact.
        /// </summary>
        public static string View_Contact_title {
            get {
                return ResourceManager.GetString("View_Contact_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Accounts.
        /// </summary>
        public static string View_terms_Accounts_title {
            get {
                return ResourceManager.GetString("View_terms_Accounts_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Terms of use.
        /// </summary>
        public static string View_Terms_page {
            get {
                return ResourceManager.GetString("View_Terms_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à See posts.
        /// </summary>
        public static string View_Voir_Posts {
            get {
                return ResourceManager.GetString("View_Voir_Posts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à At Gros Bras Inc, we strive to offer the very best in bodybuilding supplements.  With our secure website, and our premium products, Gros Bras Inc is the best solution to all your muscle needs.
        /// </summary>
        public static string Views_About_body {
            get {
                return ResourceManager.GetString("Views_About_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About us.
        /// </summary>
        public static string Views_Layout_About {
            get {
                return ResourceManager.GetString("Views_Layout_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Articles.
        /// </summary>
        public static string Views_Layout_Articles {
            get {
                return ResourceManager.GetString("Views_Layout_Articles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cart.
        /// </summary>
        public static string Views_Layout_Cart {
            get {
                return ResourceManager.GetString("Views_Layout_Cart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Contact us.
        /// </summary>
        public static string Views_Layout_Contact {
            get {
                return ResourceManager.GetString("Views_Layout_Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Forum.
        /// </summary>
        public static string Views_Layout_Forum {
            get {
                return ResourceManager.GetString("Views_Layout_Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Home.
        /// </summary>
        public static string Views_Layout_Home {
            get {
                return ResourceManager.GetString("Views_Layout_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hello.
        /// </summary>
        public static string Views_LoginPartial_Hello {
            get {
                return ResourceManager.GetString("Views_LoginPartial_Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log in.
        /// </summary>
        public static string Views_LoginPartial_LogIn {
            get {
                return ResourceManager.GetString("Views_LoginPartial_LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Log off.
        /// </summary>
        public static string Views_LoginPartial_LogOff {
            get {
                return ResourceManager.GetString("Views_LoginPartial_LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Register.
        /// </summary>
        public static string Views_LoginPartial_Register {
            get {
                return ResourceManager.GetString("Views_LoginPartial_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Description.
        /// </summary>
        public static string Views_Recommandation_Description {
            get {
                return ResourceManager.GetString("Views_Recommandation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Product.
        /// </summary>
        public static string Views_Recommandation_Product {
            get {
                return ResourceManager.GetString("Views_Recommandation_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Some services on the Sites permit or require you to create an account to participate or to secure additional benefits. You agree to provide, maintain and update true, accurate, current and complete information about yourself as prompted by our registration processes (the &quot;Registration Data&quot;). You shall not impersonate any person or entity or misrepresent your identity or affiliation with any person or entity, including using another person&apos;s username, password or other account information, or another person [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Views_terms_accounts_body {
            get {
                return ResourceManager.GetString("Views_terms_accounts_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à We have adopted and implemented a policy that provides for the termination, in appropriate circumstances as determined by us in our sole discretion, of users who are infringers of copyright.
        ///
        ///Pursuant to Title 17, United States Code, Section 512(c)(2), notifications of claimed copyright infringement must be sent to our Designated Agent.
        ///
        ///Notification must be submitted to the following Designated Agent: Sarah Smith.
        ///
        ///Full Address of Designated Agent to Which Notification Should be Sent: 5777 N. Meeker  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Views_terms_Copy_body {
            get {
                return ResourceManager.GetString("Views_terms_Copy_body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à claims of copyright infringement.
        /// </summary>
        public static string Views_terms_Copy_title {
            get {
                return ResourceManager.GetString("Views_terms_Copy_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à THE CONTENT ON OR OTHERWISE RELATED IN ANY WAY TO OUR SITES OR ANY THIRD PARTY SITES OR SERVICES LINKED TO FROM ANY SITE IS PROVIDED &quot;AS IS&quot; AND WITHOUT WARRANTIES OF ANY KIND. TO THE FULLEST EXTENT PERMISSIBLE PURSUANT TO APPLICABLE LAW, WE DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, COMPLETENESS, AVAILABILITY, SECURITY, COMPATABILITY AND NONINFRINGEMENT. WE DO NOT WARRANT THAT ANY CONTENT WILL BE ERROR-FREE, THAT ACCESS  [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        public static string Views_terms_dis_Body {
            get {
                return ResourceManager.GetString("Views_terms_dis_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à disclaimer.
        /// </summary>
        public static string Views_terms_Dis_title {
            get {
                return ResourceManager.GetString("Views_terms_Dis_title", resourceCulture);
            }
        }
    }
}
